<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <RootNamespace>HtmlPrivateTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Html5DomTest\Html5DomTest.Core.csproj" />
    <ProjectReference Include="..\HtmlDocToolTest\HtmlDocToolTest.Core.csproj" />
  </ItemGroup>

</Project>
